# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         ogd
version:      0.02
version_from: lib/ogd.pm
installdirs:  site
requires:
    B:                             0
    Scalar::Util:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
